QT_VERSION=6.11.0
QT_VERSION_FAMILY=6.11
WINDOWS_QT_SUBDIR=mingw_64
WINDOWS_QT_ARM64_SUBDIR=msvc2022_arm64
WINDOWS_QT_FALLBACK_SUBDIRS=llvm-mingw_64:msvc2022_64
MACOS_HOMEBREW_ARM_QT=/opt/homebrew/opt/qt
MACOS_HOMEBREW_INTEL_QT=/usr/local/opt/qt
MACOS_QT_ONLINE_INSTALLER_DIR=${HOME}/Qt/${QT_VERSION}/macos
LINUX_QT_CMAKE_DIRS=/usr/lib/cmake/Qt6:/usr/lib/aarch64-linux-gnu/cmake/Qt6:/usr/lib/x86_64-linux-gnu/cmake/Qt6
